spring.application.name=user-service
spring.datasource.url=jdbc:postgresql://localhost:5432/investment_system
spring.datasource.username=postgres
spring.datasource.password=admin

# ????????? ?????????????? ???????? ?????? Hibernate (?????????? Flyway)
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=false
spring.jpa.properties.hibernate.default_schema=user_service
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Flyway ???????? (????? ????????? ???????)
spring.flyway.enabled=false

# JWT
jwt.secret=change-this-secret-to-64-bytes-minimum
jwt.expiration-ms=86400000
